name = "rick-morty-cloudflare-portal"
compatibility_date = "2026-04-12"

pages_build_output_dir = "./dist"

[vars]
RICK_AND_MORTY_API_BASE_URL = "https://rickandmortyapi.com/api"
API_BASE_URL = ""
ADMIN_EMAILS = "guinho_p1@hotmail.com"
ADMIN_EDITOR_EMAILS = ""
ADMIN_VIEWER_EMAILS = ""
GEMINI_API_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
GEMINI_MODEL = "gemini-2.5-flash"

[[d1_databases]]
binding = "DB"
database_name = "rick-morty-portal"
database_id = "eef94738-d20f-480b-bdf6-2357354654e8"
